vich_uploader:
    db_driver: orm

    mappings:
        voitures_images:
            uri_prefix: /uploads/voitures
            upload_destination: '%kernel.project_dir%/public/uploads/voitures'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
